### PR TITLE
Main Curriculum HTML Forms

### PR DESCRIPTION
**Pull request by Stricks1**
Pull request for the creation of a SignUp page similar to mint.com SingUp

Coded by Gabriel Silveira and Emilio Contreras for Microverse projects on HTML & CSS3

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Congratulations on your project it looks good! 👍  
However there are some points that need to be changed.

## Changes required

- [x] We need 3 different logos with 3 texts on the right. Right now you are displaying an image showing all tree and no text (The text is on the image) Please place the logos and the text separately. 
- Mint logo and text 
- Quickbooks logo and text
- Turbotax logo and text

- [x] Remember to validate your HTML right now the validator show's errors https://validator.w3.org/#validate_by_upload

- [x] There are some repeated rules on your CSS for example some `display` rules and some `color` rules You can read this article for help: https://speckyboy.com/good-bad-css-practices/

After making the required changes please re-submit your project for another review. 

Cheers! 👍 

## Code Review by Mario Enrique Delgado Naranjo

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @emiliocm9, great job fixing the comments pointed out by the previous TSE. 👍 The project looks great 😄 Let us make the project even better by addressing the following comments:
* Kindly edit the PR (Pull Request) by checking this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The PR should be descriptive of the project
* Let us apply DRY rule by cleaning our code. Example: if we have 3 or more elements sharing the same (display: flex). We can clean it by writing in this form =>``` .first-element, .second-element, .third-element { display: flex }```. Let us go through our CSS  file and take a closer look at our code and make the changes 🙂 

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by addod19** [comment]
> ## Status: Require changes ♻️ 🚥
> Hi @emiliocm9, great job fixing the comments pointed out by the previous TSE. 👍 The project looks great 😄 Let us make the project even better by addressing the following comments:
> 
> * Kindly edit the PR (Pull Request) by checking this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The PR should be descriptive of the project
> * Let us apply DRY rule by cleaning our code. Example: if we have 3 or more elements sharing the same (display: flex). We can clean it by writing in this form =>` .first-element, .second-element, .third-element { display: flex }`. Let us go through our CSS  file and take a closer look at our code and make the changes 🙂
> 
> Kindly make these changes and submit another code review 👍
> _Happy coding_ 👨‍💻
> Daniel Larbi Addo

Hi Students, I am sorry for misleading on my grammar error. I actually meant we should apply the DRY  rule. Thank you 😄

**Comment by Stricks1** [comment]
> > ## Status: Require changes ♻️ 🚥
> > Hi @emiliocm9, great job fixing the comments pointed out by the previous TSE. 👍 The project looks great 😄 Let us make the project even better by addressing the following comments:
> > 
> > * Kindly edit the PR (Pull Request) by checking this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The PR should be descriptive of the project
> > * Let us apply DRY rule by cleaning our code. Example: if we have 3 or more elements sharing the same (display: flex). We can clean it by writing in this form =>` .first-element, .second-element, .third-element { display: flex }`. Let us go through our CSS  file and take a closer look at our code and make the changes 🙂
> > 
> > Kindly make these changes and submit another code review 👍
> > _Happy coding_ 👨‍💻
> > Daniel Larbi Addo
> 
> Hi Students, I am sorry for misleading on my grammar error. I actually meant we should apply the DRY rule. Thank you 😄

Hi @addod19 no problem, but we already did those changes on the CSS for display flex that you mentioned. Is it right now or we have any more fixes?
We will appreciate your feedback :)

**Comment by emiliocm9** [comment]
> > ## Status: Require changes ♻️ 🚥
> > Hi @emiliocm9, great job fixing the comments pointed out by the previous TSE. 👍 The project looks great 😄 Let us make the project even better by addressing the following comments:
> > 
> > * Kindly edit the PR (Pull Request) by checking this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The PR should be descriptive of the project
> > * Let us apply DRY rule by cleaning our code. Example: if we have 3 or more elements sharing the same (display: flex). We can clean it by writing in this form =>` .first-element, .second-element, .third-element { display: flex }`. Let us go through our CSS  file and take a closer look at our code and make the changes 🙂
> > 
> > Kindly make these changes and submit another code review 👍
> > _Happy coding_ 👨‍💻
> > Daniel Larbi Addo
> 
> Hi Students, I am sorry for misleading on my grammar error. I actually meant we should apply the DRY rule. Thank you 😄

Hi @addod19, thank you! We appreciate your feedback.
We have made some changes on our code

**Comment by majovanilla** [comment]
## Good job on this project! 👍

All the previous requirements have been changed.

### The status is APPROVED

You can merge with development and please submit your completion form

**Pull request merged**
